### ISSUE TITLE
autoreconf --install后的subdir-objects问题

### ISSUE THREAD

**Issue by alan717** [liuqun/njit8021xclient#13]
要在AM_INIT_AUTOMAKE()中加入
[subdir-objects]

**Comment by bitdust** [comment]
啊啊~
刚写好一个 pull request 
居然被你抢先了

**Comment by bitdust** [comment]
顺便咨询下 @liuqun 
出于何种考虑，在 njit8021xclient 项目里保留了 内置MD5库和依赖openssl的MD5库？
而且这样带来的对openssl的依赖让我很困扰。。能否把openssl的依赖给去掉？
（如果可以的话，我可以试着再pull request一个）

**Comment by liuqun** [comment]
我当时采用的内置md5方案已经去掉对libcrypto.so这个大块头DLL文件的依赖。
编译期间自行创建obj文件
fillmd5-libcrypto.c源代码中的#include <openssl/md5.h>不需要更改

**Comment by bitdust** [comment]
明白了，说明我还是没看仔细源码啊哈哈

**Comment by liuqun** [comment]
我后来发现更好的解决方案，只要手动复制正确的libxxx.a过来
然后

```gcc *.o ./libcrypto.a ./libpcap.a  -o njit-client```
